defmodule NbPingcrmWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :nb_pingcrm

  if Application.compile_env(:nb_pingcrm, :sandbox, false) do
    plug Phoenix.Ecto.SQL.Sandbox
  end

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_nb_pingcrm_key",
    signing_salt: "JwE2NNM5",
    same_site: "Lax"
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [:user_agent, session: @session_options]],
    longpoll: [connect_info: [:user_agent, session: @session_options]]

  socket "/socket", NbPingcrmWeb.UserSocket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: false

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :nb_pingcrm,
    gzip: not code_reloading?,
    only: NbPingcrmWeb.static_paths()

  if Code.ensure_loaded?(Tidewave) do
    # Skip Tidewave for internal modal base page requests (from NbInertia.Modal.HttpClient)
    plug :maybe_tidewave

    defp maybe_tidewave(conn, _opts) do
      if Plug.Conn.get_req_header(conn, "x-inertia-modal-base-request") == ["true"] do
        conn
      else
        tidewave = Tidewave
        apply(tidewave, :call, [conn, apply(tidewave, :init, [[]])])
      end
    end
  end

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :nb_pingcrm
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug NbPingcrmWeb.Router
end
