/**
 * Generated TypeScript definitions for route helpers
 * Generated by NbRoutes
 *
 * @warning DO NOT EDIT - This file is auto-generated
 */

/**
 * Valid route parameter types
 */
export type RouteParameter = string | number | boolean;

/**
 * Result returned by rich route helpers
 */
export interface RouteResult {
  /** Generated URL */
  url: string;
  /** HTTP method */
  method: 'get' | 'post' | 'patch' | 'put' | 'delete' | 'head' | 'options';
}

/**
 * Attributes for HTML form elements
 */
export interface FormAttributes {
  /** Form action URL (with method spoofing via _method parameter if needed) */
  action: string;
  /** Form method (always 'get' or 'post') */
  method: 'get' | 'post';
}

/**
 * Options that can be passed to route helpers
 */
export interface RouteOptions {
  /** URL anchor (hash) */
  anchor?: string;
  /** Query string parameters to append */
  query?: Record<string, RouteParameter>;
  /** Query string parameters to merge with existing query */
  mergeQuery?: Record<string, RouteParameter | null | undefined>;
}

/**
 * Default URL options for absolute URLs
 */
export interface DefaultUrlOptions {
  /** URL scheme (http, https) */
  scheme?: string;
  /** Host name */
  host?: string;
  /** Port number */
  port?: number;
}

/**
 * Configuration options for route generation
 */
export interface RouteConfig {
  defaultUrlOptions?: DefaultUrlOptions;
  trailingSlash?: boolean;
}

/**
 * Route helper function with method and form variants
 */
export interface RouteHelperWithForm<TParams extends any[] = any[]> {
  /** Main helper - returns RouteResult with url and method */
  (...args: TParams): RouteResult;
  /** GET method variant */
  get(...args: TParams): RouteResult;
  /** POST method variant */
  post(...args: TParams): RouteResult;
  /** PATCH method variant */
  patch(...args: TParams): RouteResult;
  /** PUT method variant */
  put(...args: TParams): RouteResult;
  /** DELETE method variant */
  delete(...args: TParams): RouteResult;
  /** HEAD method variant */
  head(...args: TParams): RouteResult;
  /** URL-only variant - returns just the URL string */
  url(...args: TParams): string;
  /** Form helper - returns FormAttributes for use with HTML forms */
  form: {
    /** Main form helper - uses the route's original HTTP method */
    (...args: TParams): FormAttributes;
    /** PATCH form variant */
    patch(...args: TParams): FormAttributes;
    /** PUT form variant */
    put(...args: TParams): FormAttributes;
    /** DELETE form variant */
    delete(...args: TParams): FormAttributes;
  };
}

/**
 * Route helper function with method variants (no form support)
 */
export interface RouteHelper<TParams extends any[] = any[]> {
  /** Main helper - returns RouteResult with url and method */
  (...args: TParams): RouteResult;
  /** GET method variant */
  get(...args: TParams): RouteResult;
  /** POST method variant */
  post(...args: TParams): RouteResult;
  /** PATCH method variant */
  patch(...args: TParams): RouteResult;
  /** PUT method variant */
  put(...args: TParams): RouteResult;
  /** DELETE method variant */
  delete(...args: TParams): RouteResult;
  /** HEAD method variant */
  head(...args: TParams): RouteResult;
  /** URL-only variant - returns just the URL string */
  url(...args: TParams): string;
}

/**
 * put /contacts/:id/restore
 *
 * @example
 * contacts_restore_path(1)
 */
export const contacts_restore_path: RouteHelperWithForm<[RouteParameter, options?: RouteOptions]>;

/**
 * get /users/settings/confirm-email/:token
 *
 * @example
 * user_settings_confirm_email_path(1)
 */
export const user_settings_confirm_email_path: RouteHelper<[RouteParameter, options?: RouteOptions]>;

/**
 * get /users/log-in
 *
 * @example
 * user_session_new_path()
 */
export const user_session_new_path: RouteHelper<[options?: RouteOptions]>;

/**
 * post /contacts
 *
 * @example
 * contacts_create_path()
 */
export const contacts_create_path: RouteHelperWithForm<[options?: RouteOptions]>;

/**
 * get /dev/dashboard/js-:md5
 *
 * @example
 * live_dashboard_asset_js_path()
 */
export const live_dashboard_asset_js_path: RouteHelper<[options?: RouteOptions]>;

/**
 * put /users/:id
 *
 * @example
 * users_users_update_path(1)
 */
export const users_users_update_path: RouteHelperWithForm<[RouteParameter, options?: RouteOptions]>;

/**
 * get /dev/dashboard/css-:md5
 *
 * @example
 * live_dashboard_asset_css_path()
 */
export const live_dashboard_asset_css_path: RouteHelper<[options?: RouteOptions]>;

/**
 * post /users/register
 *
 * @example
 * user_registration_create_path()
 */
export const user_registration_create_path: RouteHelperWithForm<[options?: RouteOptions]>;

/**
 * put /organizations/:id
 *
 * @example
 * organizations_organizations_update_path(1)
 */
export const organizations_organizations_update_path: RouteHelperWithForm<[RouteParameter, options?: RouteOptions]>;

/**
 * delete /users/log-out
 *
 * @example
 * user_session_delete_path()
 */
export const user_session_delete_path: RouteHelperWithForm<[options?: RouteOptions]>;

/**
 * put /organizations/:id/restore
 *
 * @example
 * organizations_restore_path(1)
 */
export const organizations_restore_path: RouteHelperWithForm<[RouteParameter, options?: RouteOptions]>;

/**
 * get /organizations/create
 *
 * @example
 * organizations_new_path()
 */
export const organizations_new_path: RouteHelper<[options?: RouteOptions]>;

/**
 * delete /organizations/:id
 *
 * @example
 * organizations_delete_path(1)
 */
export const organizations_delete_path: RouteHelperWithForm<[RouteParameter, options?: RouteOptions]>;

/**
 * get /contacts/create
 *
 * @example
 * contacts_new_path()
 */
export const contacts_new_path: RouteHelper<[options?: RouteOptions]>;

/**
 * put /users/:id/restore
 *
 * @example
 * users_restore_path(1)
 */
export const users_restore_path: RouteHelperWithForm<[RouteParameter, options?: RouteOptions]>;

/**
 * get /organizations
 *
 * @example
 * organizations_index_path()
 */
export const organizations_index_path: RouteHelper<[options?: RouteOptions]>;

/**
 * post /organizations
 *
 * @example
 * organizations_create_path()
 */
export const organizations_create_path: RouteHelperWithForm<[options?: RouteOptions]>;

/**
 * put /contacts/:id
 *
 * @example
 * contacts_contacts_update_path(1)
 */
export const contacts_contacts_update_path: RouteHelperWithForm<[RouteParameter, options?: RouteOptions]>;

/**
 * get /
 *
 * @example
 * page_path()
 */
export const page_path: RouteHelper<[options?: RouteOptions]>;

/**
 * delete /users/:id
 *
 * @example
 * users_delete_path(1)
 */
export const users_delete_path: RouteHelperWithForm<[RouteParameter, options?: RouteOptions]>;

/**
 * put /users/settings
 *
 * @example
 * user_settings_update_path()
 */
export const user_settings_update_path: RouteHelperWithForm<[options?: RouteOptions]>;

/**
 * get /contacts
 *
 * @example
 * contacts_index_path()
 */
export const contacts_index_path: RouteHelper<[options?: RouteOptions]>;

/**
 * delete /contacts/:id
 *
 * @example
 * contacts_delete_path(1)
 */
export const contacts_delete_path: RouteHelperWithForm<[RouteParameter, options?: RouteOptions]>;

/**
 * post /users/log-in
 *
 * @example
 * user_session_create_path()
 */
export const user_session_create_path: RouteHelperWithForm<[options?: RouteOptions]>;

/**
 * get /users/create
 *
 * @example
 * users_new_path()
 */
export const users_new_path: RouteHelper<[options?: RouteOptions]>;

/**
 * get /users
 *
 * @example
 * users_index_path()
 */
export const users_index_path: RouteHelper<[options?: RouteOptions]>;

/**
 * get /users/register
 *
 * @example
 * user_registration_new_path()
 */
export const user_registration_new_path: RouteHelper<[options?: RouteOptions]>;

/**
 * post /users
 *
 * @example
 * users_create_path()
 */
export const users_create_path: RouteHelperWithForm<[options?: RouteOptions]>;

/**
 * get /users/log-in/:token
 *
 * @example
 * user_session_confirm_path(1)
 */
export const user_session_confirm_path: RouteHelper<[RouteParameter, options?: RouteOptions]>;

/**
 * get /organizations/:id/edit
 *
 * @example
 * organizations_edit_path(1)
 */
export const organizations_edit_path: RouteHelper<[RouteParameter, options?: RouteOptions]>;

/**
 * get /users/:id/edit
 *
 * @example
 * users_edit_path(1)
 */
export const users_edit_path: RouteHelper<[RouteParameter, options?: RouteOptions]>;

/**
 * get /contacts/:id/edit
 *
 * @example
 * contacts_edit_path(1)
 */
export const contacts_edit_path: RouteHelper<[RouteParameter, options?: RouteOptions]>;

/**
 * get /users/settings
 *
 * @example
 * user_settings_edit_path()
 */
export const user_settings_edit_path: RouteHelper<[options?: RouteOptions]>;

/**
 * Configure route generation options
 *
 * @param options - Configuration options
 *
 * @example
 * configure({
 *   defaultUrlOptions: {
 *     scheme: 'https',
 *     host: 'example.com'
 *   }
 * });
 */
export function configure(options: RouteConfig): void;

/**
 * Get current configuration
 *
 * @returns Current route configuration
 */
export function config(): RouteConfig;

/**
 * Build URL from pattern and params (low-level helper)
 *
 * @param pattern - URL pattern with :param placeholders (e.g., "/users/:id")
 * @param params - Parameter values (e.g., { id: 1 })
 * @param options - URL options (query, mergeQuery, anchor)
 * @returns Built URL string
 *
 * @example
 * _buildUrl("/users/:id", { id: 123 }, { query: { filter: "active" } })
 * // => "/users/123?filter=active"
 */
export function _buildUrl(
  pattern: string,
  params?: Record<string, RouteParameter>,
  options?: RouteOptions
): string;

/**
 * Visit options for Inertia.js (subset of available options)
 */
export interface InertiaVisitOptions {
  /** The method to use for the request */
  method?: 'get' | 'post' | 'put' | 'patch' | 'delete';
  /** The data to send with the request */
  data?: Record<string, any>;
  /** Replace the current history state */
  replace?: boolean;
  /** Preserve the scroll position */
  preserveScroll?: boolean | ((props: any) => boolean);
  /** Preserve the component's local state */
  preserveState?: boolean | ((props: any) => boolean);
  /** Only fetch these props from the server */
  only?: string[];
  /** Additional headers to include */
  headers?: Record<string, string>;
  /** Error bag to use */
  errorBag?: string | null;
  /** Force a form data request */
  forceFormData?: boolean;
  /** Callbacks */
  onBefore?: (visit: any) => void;
  onStart?: (visit: any) => void;
  onProgress?: (progress: any) => void;
  onSuccess?: (page: any) => void;
  onError?: (errors: any) => void;
  onCancel?: () => void;
  onFinish?: () => void;
}

/**
 * Visit a route using Inertia.js router
 *
 * @param route - Route result from a rich mode helper (e.g., users_path())
 * @param options - Inertia visit options (data, headers, preserveScroll, etc.)
 * @returns Inertia visit promise
 *
 * @example
 * import { users_path, visitRoute } from './routes';
 *
 * // Simple navigation
 * visitRoute(users_path());
 *
 * // With additional options
 * visitRoute(update_user_path.patch(user.id), {
 *   data: formData,
 *   preserveScroll: true
 * });
 */
export function visitRoute(
  route: RouteResult,
  options?: Omit<InertiaVisitOptions, 'method'>
): Promise<any>;