/**
 * NbFlop TypeScript Types
 *
 * These types match the serializers generated by nb_flop.
 * They integrate with nb_ts for automatic type generation.
 */

// Flop filter operators
export type FlopOperator =
  | '=='
  | '!='
  | '<'
  | '<='
  | '>'
  | '>='
  | '=~'
  | 'like'
  | 'not_like'
  | 'ilike'
  | 'not_ilike'
  | 'like_and'
  | 'like_or'
  | 'ilike_and'
  | 'ilike_or'
  | 'in'
  | 'not_in'
  | 'contains'
  | 'not_contains'
  | 'empty'
  | 'not_empty';

// Flop filter structure
// Accepts both typed FlopOperator and plain strings from serializer
export interface FlopFilter {
  field: string;
  op: FlopOperator | string;
  value: unknown;
}

// Sort direction
export type SortDirection = 'asc' | 'desc' | null;

// Order direction (extended for nulls handling)
export type OrderDirection =
  | 'asc'
  | 'desc'
  | 'asc_nulls_first'
  | 'asc_nulls_last'
  | 'desc_nulls_first'
  | 'desc_nulls_last';

// Flop params structure (query parameters)
export interface FlopParams {
  // Ordering
  orderBy?: string[] | null;
  orderDirections?: (OrderDirection | string)[] | null;

  // Page-based pagination
  page?: number | null;
  pageSize?: number | null;

  // Offset-based pagination
  offset?: number | null;
  limit?: number | null;

  // Cursor-based pagination
  first?: number | null;
  last?: number | null;
  after?: string | null;
  before?: string | null;

  // Filters
  filters?: FlopFilter[];
}

// Filterable field metadata
// Accepts both typed FlopOperator and plain strings from serializer
export interface FilterableField {
  field: string;
  label: string;
  type: 'string' | 'number' | 'boolean' | 'date' | 'datetime' | 'array' | 'enum';
  operators: (FlopOperator | string)[];
}

// Flop meta structure (pagination info)
// This interface is compatible with both auto-generated FlopMeta from nb_ts
// and the manually-defined component props
export interface FlopMeta {
  // Page-based pagination
  currentPage: number | null;
  totalPages: number | null;
  previousPage: number | null;
  nextPage: number | null;

  // Offset-based pagination
  currentOffset: number | null;
  previousOffset: number | null;
  nextOffset: number | null;

  // Cursor-based pagination
  startCursor: string | null;
  endCursor: string | null;

  // Shared
  hasPreviousPage: boolean;
  hasNextPage: boolean;
  pageSize: number | null;
  totalCount: number | null;

  // Flop params used in query
  flop: FlopParams;

  // Schema introspection (when schema option provided)
  filterableFields?: FilterableField[];
  sortableFields?: string[];
}

// Pagination mode detection
export type PaginationMode = 'page' | 'offset' | 'cursor';

// Component props
export interface PaginationProps {
  meta: FlopMeta;
  onPageChange: (page: number) => void;
  className?: string;
  showPageNumbers?: boolean;
  maxVisiblePages?: number;
  labels?: {
    previous?: string;
    next?: string;
    page?: (current: number, total: number) => string;
  };
}

export interface CursorPaginationProps {
  meta: FlopMeta;
  onNext: () => void;
  onPrevious: () => void;
  className?: string;
  loadingNext?: boolean;
  loadingPrevious?: boolean;
  labels?: {
    previous?: string;
    next?: string;
    loadingPrevious?: string;
    loadingNext?: string;
  };
}

export interface SortableHeaderProps {
  field: string;
  children: React.ReactNode;
  currentSort?: string | null;
  currentDirection?: SortDirection;
  onSort: (field: string, direction: SortDirection) => void;
  className?: string;
  ascIcon?: React.ReactNode;
  descIcon?: React.ReactNode;
  unsortedIcon?: React.ReactNode;
}

export interface FilterFormRenderProps {
  fields: FilterableField[];
  activeFilters: FlopFilter[];
  setFilter: (field: string, op: FlopOperator, value: unknown) => void;
  removeFilter: (field: string, op?: FlopOperator) => void;
  clearFilters: () => void;
}

export interface FilterFormProps {
  filterableFields?: FilterableField[];
  filters?: FlopFilter[];
  onFilterChange: (field: string, op: FlopOperator, value: unknown) => void;
  onFilterRemove: (field: string, op?: FlopOperator) => void;
  onClearFilters: () => void;
  className?: string;
  children?: (props: FilterFormRenderProps) => React.ReactNode;
}

// Linear-style filter types

export type FilterFieldType =
  | 'string'
  | 'boolean'
  | 'enum'
  | 'relation'
  | 'date'
  | 'number';

export interface FilterOption {
  value: string | number;
  label: string;
  icon?: React.ComponentType<{ className?: string }>;
}

export interface FilterConfig {
  field: string;
  label: string;
  type: FilterFieldType;
  operators: (FlopOperator | string)[];
  icon?: React.ComponentType<{ className?: string }>;
  options?: FilterOption[];
  optionsKey?: string; // key in filterOptions props for dynamic options
  customParam?: string; // for non-Flop filters (role, trashed)
  placeholder?: string;
}

export type FilterMode = 'all' | 'any';

export interface ActiveFilter {
  config: FilterConfig;
  operator: FlopOperator | string;
  value: unknown;
}

export interface FilterBarProps {
  configs: FilterConfig[];
  filters: FlopFilter[];
  customFilters?: Record<string, unknown>;
  filterOptions?: Record<string, FilterOption[]>;
  filterMode: FilterMode;
  onFilterChange: (field: string, op: FlopOperator | string, value: unknown) => void;
  onFilterRemove: (field: string, op?: FlopOperator | string) => void;
  onCustomFilterChange?: (param: string, value: unknown) => void;
  onClearFilters: () => void;
  onFilterModeChange: (mode: FilterMode) => void;
  className?: string;
}

export interface FilterChipProps {
  config: FilterConfig;
  operator: FlopOperator | string;
  value: unknown;
  filterOptions?: FilterOption[];
  onOperatorChange: (op: FlopOperator | string) => void;
  onValueChange: (value: unknown) => void;
  onRemove: () => void;
}

export interface AddFilterButtonProps {
  configs: FilterConfig[];
  filterOptions?: Record<string, FilterOption[]>;
  onAddFilter: (field: string, op: FlopOperator | string, value: unknown) => void;
}

export interface FilterValueSelectProps {
  options: FilterOption[];
  value?: unknown;
  onSelect: (value: unknown) => void;
  placeholder?: string;
}

export interface FilterValueInputProps {
  value?: string;
  onChange: (value: string) => void;
  placeholder?: string;
  type?: 'text' | 'number' | 'date';
}

export interface FilterModeToggleProps {
  mode: FilterMode;
  onChange: (mode: FilterMode) => void;
}

// TanStack Table integration types

export interface SortableColumnHeaderProps {
  /** The field name to sort by (should match Flop schema sortable field) */
  field: string;
  /** Column header content */
  children: React.ReactNode;
  /** Icon for ascending sort */
  ascIcon?: React.ReactNode;
  /** Icon for descending sort */
  descIcon?: React.ReactNode;
  /** Icon for unsorted state */
  unsortedIcon?: React.ReactNode;
  /** Additional className for the button */
  className?: string;
}
