defmodule NbPingcrm.Examples.Item do
  @moduledoc """
  Example schema for demonstrating the NbFlop Table DSL.

  Generated by nb_flop. This is a sample - create your own schemas
  and run migrations to use real data.
  """

  use Ecto.Schema
  import Ecto.Changeset

  @derive {
    Flop.Schema,
    filterable: [:name, :email, :status], sortable: [:name, :email, :status, :inserted_at]
  }

  schema "example_items" do
    field :name, :string
    field :email, :string
    field :status, :string, default: "active"

    timestamps()
  end

  @doc false
  def changeset(item, attrs) do
    item
    |> cast(attrs, [:name, :email, :status])
    |> validate_required([:name, :email])
    |> validate_inclusion(:status, ["active", "inactive"])
  end
end
