defmodule NbPingcrmWeb.Serializers.FilterableFieldSerializer do
  @moduledoc """
  Serializes filterable field metadata.

  Generated by nb_flop. Customize as needed.
  """

  use NbSerializer.Serializer

  schema do
    field :field, :string
    field :label, :string
    field :type, enum: ["string", "number", "boolean", "date", "datetime", "array", "enum"]
    field :operators, list: :string
  end
end
