defmodule NbPingcrmWeb.Serializers.FlopMetaSerializer do
  @moduledoc """
  Serializes Flop.Meta with schema introspection.

  Generated by nb_flop. Customize as needed.

  ## Usage

      render_inertia(conn, :posts_index,
        posts: {PostSerializer, posts},
        meta: {FlopMetaSerializer, meta, schema: Post}
      )

  The `schema` option enables sortable/filterable field introspection.
  """

  use NbSerializer.Serializer

  alias NbPingcrmWeb.Serializers.FilterableFieldSerializer
  alias NbPingcrmWeb.Serializers.FlopParamsSerializer

  schema do
    # Page-based pagination
    field(:current_page, :number, nullable: true)
    field(:total_pages, :number, nullable: true)
    field(:previous_page, :number, nullable: true)
    field(:next_page, :number, nullable: true)

    # Offset-based pagination
    field(:current_offset, :number, nullable: true)
    field(:previous_offset, :number, nullable: true)
    field(:next_offset, :number, nullable: true)

    # Cursor-based pagination
    field(:start_cursor, :string, nullable: true)
    field(:end_cursor, :string, nullable: true)

    # Shared
    field(:has_previous_page, :boolean, from: :has_previous_page?)
    field(:has_next_page, :boolean, from: :has_next_page?)
    field(:page_size, :number, nullable: true)
    field(:total_count, :number, nullable: true)

    # Flop params
    has_one(:flop, FlopParamsSerializer)

    # Schema introspection
    field(:filterable_fields,
      list: FilterableFieldSerializer,
      compute: :compute_filterable_fields,
      optional: true
    )

    field(:sortable_fields,
      list: :string,
      compute: :compute_sortable_fields,
      optional: true
    )
  end

  def compute_filterable_fields(_meta, opts) do
    case Keyword.get(opts, :schema) do
      nil ->
        nil

      schema ->
        if Code.ensure_loaded?(Flop.Schema) and
             function_exported?(Flop.Schema, :filterable, 1) do
          try do
            schema
            |> Flop.Schema.filterable()
            |> build_filterable_fields(schema)
          rescue
            _ -> nil
          end
        else
          nil
        end
    end
  end

  def compute_sortable_fields(_meta, opts) do
    case Keyword.get(opts, :schema) do
      nil ->
        nil

      schema ->
        if Code.ensure_loaded?(Flop.Schema) and
             function_exported?(Flop.Schema, :sortable, 1) do
          try do
            schema
            |> Flop.Schema.sortable()
            |> Enum.map(&to_string/1)
          rescue
            _ -> nil
          end
        else
          nil
        end
    end
  end

  defp build_filterable_fields(fields, schema) do
    Enum.map(fields, fn field ->
      %{
        field: to_string(field),
        label: field |> to_string() |> String.replace("_", " ") |> String.capitalize(),
        type: infer_type(schema, field),
        operators: infer_operators(schema, field)
      }
    end)
  end

  defp infer_type(schema, field) do
    case schema.__schema__(:type, field) do
      :boolean -> "boolean"
      type when type in [:integer, :float, :decimal] -> "number"
      type when type in [:date, :naive_datetime, :utc_datetime] -> "datetime"
      {:array, _} -> "array"
      {:parameterized, Ecto.Enum, _} -> "enum"
      _ -> "string"
    end
  rescue
    _ -> "string"
  end

  defp infer_operators(_schema, _field) do
    # Default operators - customize per field type if needed
    ["==", "!=", "=~", "ilike", "empty", "not_empty"]
  end
end
