defmodule NbPingcrmWeb.Serializers.FlopFilterSerializer do
  @moduledoc """
  Serializes Flop.Filter structs.

  Generated by nb_flop. Customize as needed.
  """

  use NbSerializer.Serializer

  schema do
    field :field, :string
    field :op, :string, compute: :compute_op
    field :value, :any
  end

  def compute_op(filter, _opts) do
    case filter.op do
      op when is_atom(op) -> Atom.to_string(op)
      op -> op
    end
  end
end
