defmodule NbPingcrmWeb.Serializers.FlopParamsSerializer do
  @moduledoc """
  Serializes Flop query parameters.

  Generated by nb_flop. Customize as needed.
  """

  use NbSerializer.Serializer

  alias NbPingcrmWeb.Serializers.FlopFilterSerializer

  schema do
    # Ordering
    field :order_by, list: :string, compute: :compute_order_by, optional: true
    field :order_directions, list: :string, compute: :compute_order_directions, optional: true

    # Page-based pagination
    field :page, :number, optional: true, nullable: true
    field :page_size, :number, optional: true, nullable: true

    # Offset-based pagination
    field :offset, :number, optional: true, nullable: true
    field :limit, :number, optional: true, nullable: true

    # Cursor-based pagination
    field :first, :number, optional: true, nullable: true
    field :last, :number, optional: true, nullable: true
    field :after, :string, optional: true, nullable: true
    field :before, :string, optional: true, nullable: true

    # Filters
    has_many :filters, FlopFilterSerializer
  end

  def compute_order_by(flop, _opts) do
    case flop.order_by do
      nil -> nil
      fields when is_list(fields) -> Enum.map(fields, &to_string/1)
    end
  end

  def compute_order_directions(flop, _opts) do
    case flop.order_directions do
      nil -> nil
      dirs when is_list(dirs) -> Enum.map(dirs, &Atom.to_string/1)
    end
  end
end
