// Inertia.js integration with nb_routes support (React)
//
// Official Inertia's Link already supports RouteResult objects natively.
// The router export comes from nb_inertia so modal-originated requests
// automatically carry modal headers.
//
// nb_inertia adds: useForm with route binding, Head/usePage with modal context
//
// Example:
//   import { router, Link, useForm, usePage, Head } from '@/lib/inertia';
//   import { user_path } from '@/routes';
//
//   router.visit(user_path(1));           // Works with RouteResult objects
//   <Link href={user_path(1)}>User</Link> // Works with RouteResult objects

export { router } from '@nordbeam/nb-inertia/react/router';
export { Link } from '@inertiajs/react';

// nb_inertia - useForm with route binding
export { useForm } from '@nordbeam/nb-inertia/react/useForm';

// nb_inertia - Head with modal context support
export { Head } from '@nordbeam/nb-inertia/react/Head';

// Note: RouteResult type is defined in @/routes.d.ts (generated by nb_routes)
// Don't re-export from nb_inertia to avoid type conflicts

// Modal hooks and integration from nb_inertia (hook-first API)
export {
  // Enhanced usePage that works in modals
  usePage,
  // Integration component - handles _nb_modal prop and navigation events
  InitialModalHandler,
  // SSR-safe modal link wrapper
  ClientModalLink,
  Modal,
  // Link component that triggers modal fetches
  ModalLink,
  // Context providers and hooks
  ModalStackProvider,
  ModalPageProvider,
  useModalStack,
  useModal,
  useCurrentModal,
  useIsInModal,
  useModalPageContext,
  // Types and config
  DEFAULT_MODAL_CONFIG,
  mergeModalConfig,
} from '@nordbeam/nb-inertia/react/modals';

// Re-export types
export type {
  ModalConfig,
  ModalSize,
  ModalPosition,
  ModalInstance,
  ModalStackContextValue,
  InitialModalHandlerProps,
  ModalOnBase,
} from '@nordbeam/nb-inertia/react/modals';

// Custom ModalStackRenderer using shadcn (copied from nb_inertia, customizable)
export { ModalStackRenderer } from '@/components/modals';

// Re-export other utilities from Inertia
export {
  useRemember,
  usePoll,
  createInertiaApp,
  http,
  config,
  WhenVisible,
} from '@inertiajs/react';
